title: Мобильное приложение Naumen SMP, версия 12
syntax: XML
supportedLanguages: []
properties: []
relatedLinks: []
name: smp-mk
style: purple-blue
code: "MK"
filterProperties: []
versions:
  - "[0-9]*"
